### PR TITLE
Minor enhancements to plist-cil

### PR DESCRIPTION
**Pull request by qmfrederik**
Hi,

I used plist-cil and encoutered some minor issues; so here is a pull request which should address them:

* An empty array (of size 0) could not be serialized using the `BinaryPropertyListWriter` because there was a check for a 0-integer value. I changed it to check for negative values; the code now passes.
* The order in which IDs are generated differs from the way the Apple libraries generate IDs (they generate IDs first for the keys and then for the values). I updated the code so that it follows the same pattern as Apple's code - ensuring binary compatibility.
* plist-cil was not strong named; my assembly was; so I added a strong name to the plist-cil project

### CODE REVIEW

**Comment by claunia** [comment]
Hi @qmfrederik. Everything seems good.
Can you please add a test case for the duplicate UID case?

**Comment by claunia** [comment]
@3breadt do you think dd-plist can benefit from these enhancements?

**Comment by qmfrederik** [comment]
Hi @claunia ,

Cool, thx. I'll try to send you a PR with a unit test; if you don't get one, feel free to ping me :-)

**Comment by 3breadt** [comment]
Some of the improvements really make sense and would benefit [dd-plist](https://github.com/3breadt/dd-plist). But I am not sure whether equivalent arrays really should be saved multiple times. Is that also just for binary compatibility with the plists produced by Apple's code?

**Pull request merged**
